JavaScript Constructors Nathan Chon
Nathan-Chon/rc0123-code-solutions pull request #69
Opened 2023-02-21 18:24 UTC by Nathan-Chon

![animation42](https://user-images.githubusercontent.com/121650766/220428264-d43d6c75-6c72-4f3c-ba63-a11b88db6523.gif)

2023-02-21 21:20 UTC, robgmerrill requested changes
Close! A couple small changes requested!

2023-02-21 21:20 UTC, robgmerrill commented on javascript-constructors/example-constructor.js
> +
per the instructions we should be using the `prototype` property. The `.getPrototypeOf()` method is going to get the prototype of `ExampleConstructor`. That would be the object that `ExampleConstructor` is inheriting from. Instead we want the `prototype` property which will be the object that it's children inherit from. 

eg: `ExampleConstructor.prototype`

2023-02-21 21:20 UTC, robgmerrill commented on javascript-constructors/example-constructor.js
> +console.log('typeof prototype:', typeof Object.getPrototypeOf(ExampleConstructor));
Same comment as on line 4

2023-02-21 21:20 UTC, robgmerrill commented on javascript-constructors/example-constructor.js
> +
We also want to log the `typeof` `afunction`.

2023-02-21 21:20 UTC, robgmerrill commented on javascript-constructors/example-constructor.js
> +var afunction = new ExampleConstructor();
Consider renaming. When we call a constructor function it creates an object. A variable name such as `anObject` might be a better indicator of the value it holds.

2023-02-22 01:24 UTC, Nathan-Chon commented
![image](https://user-images.githubusercontent.com/121650766/220496672-595023f7-bb76-4556-b7ff-fd7ec65b1188.png)
Revised version resubmitted

2023-02-22 13:02 UTC, robgmerrill approved these changes
👍

2023-02-22 17:01 UTC, merged