JavaScript Timers Nathan Chon
Nathan-Chon/rc0123-code-solutions pull request #72
Opened 2023-02-22 17:45 UTC by Nathan-Chon

![animation43](https://user-images.githubusercontent.com/121650766/220711964-49eb7578-4f6c-4d03-b271-c4e75eba98ae.gif)

2023-02-22 17:59 UTC, robgmerrill requested changes
Almost! You will need to pass a timer ID to the clearInterval function.

2023-02-22 17:59 UTC, robgmerrill commented on javascript-timers/interval.js
> +setInterval(countdown, 1000);
To capture the id we can do the following: 

`var timerId = setInterval(countdown, 1000);`

You will then pass this to the `clearInterval()` function.

2023-02-22 18:17 UTC, Nathan-Chon commented
![animation43](https://user-images.githubusercontent.com/121650766/220719884-a7b98fd1-db95-4230-945d-6607e24c10e9.gif)
Revised version timerId

2023-02-23 22:16 UTC, robgmerrill approved these changes
👍

2023-02-23 22:30 UTC, merged